### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by DaniloMurbach** [garutilorenzo/docker-swarm-ingress#1]
Hi, I'm just following the logs, there is nothing breaking (apparently) but there is those errors messages.

Mostly that under caugth my attention.

```docker.errors.APIError: 500 Server Error: Internal Server Error ("b'{"message":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}'") ```

I'm attaching the previous messages before that API 500 Server Error.

```
2022/11/15 11:21:50 [error] 65877#65877: *529600 open() "/usr/share/nginx/html/info.php" failed (2: No such file or directory), client: 10.0.10.12, server: _, request: "GET /info.php HTTP/1.1", host: "45.32.64.204"

2022/11/15 11:21:50 [error] 65877#65877: *529601 open() "/usr/share/nginx/html/.env" failed (2: No such file or directory), client: 10.0.10.14, server: _, request: "GET /.env HTTP/1.1", host: "45.32.64.204"

2022/11/15 11:21:50 [error] 65877#65877: *529602 open() "/usr/share/nginx/html/config.json" failed (2: No such file or directory), client: 10.0.10.14, server: _, request: "GET /config.json HTTP/1.1", host: "45.32.64.204"

2022/11/15 11:21:50 [error] 65877#65877: *529603 open() "/usr/share/nginx/html/about" failed (2: No such file or directory), client: 10.0.10.12, server: _, request: "GET /about HTTP/1.1", host: "45.32.64.204"

2022/11/15 11:21:50 [error] 65877#65877: *529604 open() "/usr/share/nginx/html/v2/_catalog" failed (2: No such file or directory), client: 10.0.10.12, server: _, request: "GET /v2/_catalog HTTP/1.1", host: "45.32.64.204"

2022/11/15 11:21:50 [error] 65877#65877: *529605 open() "/usr/share/nginx/html/login.action" failed (2: No such file or directory), client: 10.0.10.14, server: _, request: "GET /login.action HTTP/1.1", host: "45.32.64.204"

2022/11/15 11:21:50 [error] 65877#65877: *529606 open() "/usr/share/nginx/html/api/search" failed (2: No such file or directory), client: 10.0.10.14, server: _, request: "GET /api/search?folderIds=0 HTTP/1.1", host: "45.32.64.204"

[Ingress Auto Configuration] Services have changed, updating nginx configuration...

Traceback (most recent call last):

  File "/usr/lib/python3.9/site-packages/docker/client.py", line 170, in _raise_for_status

    response.raise_for_status()

  File "/usr/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.24/services

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/ingress/ingress.py", line 65, in <module>

    services = cli.services()

  File "/usr/lib/python3.9/site-packages/docker/utils/decorators.py", line 35, in wrapper

    return f(self, *args, **kwargs)

  File "/usr/lib/python3.9/site-packages/docker/api/service.py", line 62, in services

    return self._result(self._get(url, params=params), True)

  File "/usr/lib/python3.9/site-packages/docker/client.py", line 178, in _result

    self._raise_for_status(response)

  File "/usr/lib/python3.9/site-packages/docker/client.py", line 174, in _raise_for_status

    raise errors.APIError(e, response, explanation=explanation)

docker.errors.APIError: 500 Server Error: Internal Server Error ("b'{"message":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}'")
```

Thanks

**Comment by garutilorenzo** [comment]
Hi @DaniloMurbach what is your cluster setup?
Your swarm has a minimum amount of nodes reachable? (min. 3 noes)
The error seems to be related to a loss of quorum on the swarm cluster..

**Comment by DaniloMurbach** [comment]
Hi @garutilorenzo thanks for you reseponse. 

That was the issue endeed, thanks.
